apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-manager
spec:
  replicas: 5
  selector:
    matchLabels:
      app: customer-manager
  template:
    metadata:
      labels:
        app: customer-manager
    spec:
      containers:
        - name: customer-manager
          image: mybank/customer-manager:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-db-service:5432/customer_manager
            - name: SPRING_DATASOURCE_USERNAME
              value: leandro
            - name: SPRING_DATASOURCE_PASSWORD
              value: senha
---
apiVersion: v1
kind: Service
metadata:
  name: customer-manager
spec:
  type: NodePort
  selector:
    app: customer-manager
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080